image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Create .env file & Build and Push Docker Image
        script:
          - echo "GEMINI_API_KEY=${GEMINI_API_KEY}" >> .env
          - docker build -t ${DOCKERHUB_USERNAME}/latihan-be-ci:1.0.0 .
          - docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
          - docker push ${DOCKERHUB_USERNAME}/latihan-be-ci:1.0.0
        services:
          - docker
        caches:
          - docker
    - step:
        name : Deploy to EC2 AWS
        script:
          - pipe: atlassian/ssh-run:0.8.1
            variables:
              SSH_USER: $EC2_USER
              SERVER: $EC2_HOST
              SSH_KEY : $SSH_KEY
              COMMAND: |
                docker pull image ${DOCKERHUB_USERNAME}/latihan-be-ci:1.0.0
                docker stop be-products || true
                docker rm -f be-products || true
                docker run -d --name be-products -p 8000:8000 ${DOCKERHUB_USERNAME}/latihan-be-ci:1.0.0